name: Basic-Build
# Workflow file for basic builds
on:
  push:
  #   branches:
  #     - master
  pull_request: {}
  workflow_dispatch:

jobs:
  Linux:
    name: build-linux
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils

    - name: Cache depends
      id: cache-depends
      uses: actions/cache@v2
      with:
        path: depends
        key: ${{ runner.os }}-depends      

    - name: Build depends
      run: |
        cd depends
        make -j $(nproc)

    - name: Build Dash Core
      run: |
        ./autogen.sh
        ./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu
        make -j $(nproc)

    - name: View results
      run: ls src/