name: Basic-Build
# Workflow file for basic builds
on:
  push:
  #   branches:
  #     - master
  pull_request: {}
  workflow_dispatch:

jobs:
  Linux:
    name: build-linux
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build depends
      run: |
        cd depends
        make -j $(nproc)

    - name: Build Dash Core
      run: |
        cd ..
        ./autogen.sh
        ./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu
        make -j $(nproc)

    - name: View results
      run: ls src/